# Generated by Django 5.0.6 on 2024-09-03 04:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener 9 dígitos', regex='^\\d{9}$')])),
                ('dni', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe contener 8 dígitos', regex='^\\d{8}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener 9 dígitos', regex='^\\d{9}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=5)),
                ('color', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=100)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_canfel.propietario')),
                ('vacunas', models.ManyToManyField(blank=True, to='website_canfel.vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_canfel.mascota')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_canfel.propietario')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_canfel.veterinario')),
            ],
        ),
    ]
